In [1]:
import pandas as pd
from pathlib import Path

df0_AAA = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\AAA_normalized1_0.0.csv")
df0_CCC = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\CCC_normalized1_0.0.csv")
df0_DDD = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\DDD_normalized1_0.0.csv")
df0_EEE = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\EEE_normalized1_0.0.csv")
df0_FFF = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\FFF_normalized1_0.0.csv")
df0_GGG = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\GGG_normalized1_0.0.csv")
df0_BBB = pd.read_csv(r"D:\myx\Data science project·\outputs\normalized_module_csvs\BBB_normalized1_0.0.csv")
df0_ABCD = pd.concat([df0_AAA, df0_BBB, df0_CCC,df0_DDD], axis=0, ignore_index=True)
df0_CD= pd.concat([df0_CCC,df0_DDD], axis=0, ignore_index=True)

base_path = Path(r"D:\myx\Data science project·\outputs\normalized_module_csvs\fused_scaled")
# 25% 
df25_AAA = pd.read_csv(base_path / "AAA_normalized1_fused_scaled.csv")
df25_BBB = pd.read_csv(base_path / "BBB_normalized1_fused_scaled.csv")
df25_CCC = pd.read_csv(base_path / "CCC_normalized1_fused_scaled.csv")
df25_DDD = pd.read_csv(base_path / "DDD_normalized1_fused_scaled.csv")
df25_EEE = pd.read_csv(base_path / "EEE_normalized1_fused_scaled.csv")
df25_FFF = pd.read_csv(base_path / "FFF_normalized1_fused_scaled.csv")
df25_GGG = pd.read_csv(base_path / "GGG_normalized1_fused_scaled.csv")
df25_ABCD = pd.concat([df25_AAA, df25_BBB, df25_CCC, df25_DDD], axis=0, ignore_index=True)
df25_CD= pd.concat([df25_CCC,df25_DDD], axis=0, ignore_index=True)
# 50% 
df50_AAA = pd.read_csv(base_path / "AAA_normalized1_0.5_fused_scaled.csv")
df50_BBB = pd.read_csv(base_path / "BBB_normalized1_0.5_fused_scaled.csv")
df50_CCC = pd.read_csv(base_path / "CCC_normalized1_0.5_fused_scaled.csv")
df50_DDD = pd.read_csv(base_path / "DDD_normalized1_0.5_fused_scaled.csv")
df50_FFF = pd.read_csv(base_path / "FFF_normalized1_0.5_fused_scaled.csv")
df50_ABCD = pd.concat([df50_AAA, df50_BBB, df50_CCC, df50_DDD], axis=0, ignore_index=True)
df50_CD= pd.concat([df50_CCC,df50_DDD], axis=0, ignore_index=True)
# 75% 
df75_AAA = pd.read_csv(base_path / "AAA_normalized1_0.75_fused_scaled.csv")
df75_BBB = pd.read_csv(base_path / "BBB_normalized1_0.75_fused_scaled.csv")
df75_CCC = pd.read_csv(base_path / "CCC_normalized1_0.75_fused_scaled.csv")
df75_DDD = pd.read_csv(base_path / "DDD_normalized1_0.75_fused_scaled.csv")
df75_FFF = pd.read_csv(base_path / "FFF_normalized1_0.75_fused_scaled.csv")
df75_ABCD = pd.concat([df75_AAA, df75_BBB, df75_CCC, df75_DDD], axis=0, ignore_index=True)
df75_CD= pd.concat([df75_CCC,df75_DDD], axis=0, ignore_index=True)

In [2]:
import pandas as pd

df = pd.read_csv(r"D:\myx\Data science project·\rq1_df1.csv")

result_distribution = df.groupby('code_module')['final_result'].value_counts().unstack().fillna(0).astype(int)

print(result_distribution)

final_result  Distinction  Fail  Pass  Withdrawn
code_module                                     
AAA                    44    81   486         74
BBB                   677  1421  3064        613
CCC                   498   662  1175        646
DDD                   382  1184  2217        870
EEE                   356   401  1288        199
FFF                   670  1457  2975        841
GGG                   263   289   730         63


In [3]:
def get_x_y(df, classification_mode='multi'):
    
    # drop_ivs = ['Unnamed: 0', 'code_module', 'code_presentation', 'id_student',
    #             'final_result', 'date_registration', 'date_unregistration','region']

    drop_ivs = ['Unnamed: 0', 'code_module', 'code_presentation', 'id_student',
                'final_result', 'date_registration', 'date_unregistration']

    # drop_VLE_ivs = [
    #     'n_days_dataplus', 'n_days_glossary', 'n_days_oucollaborate',
    #     'sum_clicks_dataplus', 'sum_clicks_glossary', 'sum_clicks_oucollaborate',
    #     'total_n_days', 'total_sum_clicks', 'module_presentation_length',
    #     'cutoff_day', 'year', 'semester'
    # ]

#     drop_VLE_ivs = [
#        'n_days_glossary',  'n_days_oucollaborate',
#        'n_days_ouelluminate', 
#        'n_days_sharedsubpage', 
#        'n_days_dataplus', 'n_days_dualpane', 'n_days_repeatactivity', 
#  'n_days_externalquiz', 'n_days_folder', 'n_days_htmlactivity', 'n_days_ouwiki', 'n_days_page', 'n_days_questionnaire',
#         'sum_clicks_glossary',  'sum_clicks_dataplus', 'sum_clicks_dualpane', 'sum_clicks_externalquiz', 'sum_clicks_folder',
#        'sum_clicks_oucollaborate',  'sum_clicks_htmlactivity',  'sum_clicks_ouwiki', 'sum_clicks_page', 'sum_clicks_questionnaire', 
#         'sum_clicks_ouelluminate',  
#        'sum_clicks_repeatactivity', 'sum_clicks_sharedsubpage', 
#         'total_n_days',
#        'total_sum_clicks', 'module_presentation_length', 'cutoff_day',
#        'year', 'semester', 'V_LPB','V_LCB', 'V_KAB', 'V_ILB']

    drop_VLE_ivs = [
       'n_days_glossary',  'n_days_oucollaborate',
       'n_days_ouelluminate', 
       'n_days_sharedsubpage', 
       'n_days_dataplus', 'n_days_dualpane', 'n_days_repeatactivity', 
 'n_days_externalquiz', 'n_days_folder', 'n_days_htmlactivity', 'n_days_ouwiki', 'n_days_page', 'n_days_questionnaire',
        'sum_clicks_glossary',  'sum_clicks_dataplus', 'sum_clicks_dualpane', 'sum_clicks_externalquiz', 'sum_clicks_folder',
       'sum_clicks_oucollaborate',  'sum_clicks_htmlactivity',  'sum_clicks_ouwiki', 'sum_clicks_page', 'sum_clicks_questionnaire', 
        'sum_clicks_ouelluminate',  
       'sum_clicks_repeatactivity', 'sum_clicks_sharedsubpage', 
        'total_n_days',
       'total_sum_clicks', 'module_presentation_length', 'cutoff_day',
       'year', 'semester']


    drop_fused_raw = [
    'sum_clicks_homepage', 'n_days_homepage',
    'sum_clicks_resource', 'n_days_resource',
    'sum_clicks_oucontent', 'n_days_oucontent',
    'sum_clicks_url', 'n_days_url',
    'sum_clicks_forumng', 'n_days_forumng',
    'sum_clicks_ouwiki', 'n_days_ouwiki',
    'sum_clicks_subpage', 'n_days_subpage',
    'sum_clicks_quiz', 'n_days_quiz'
]


    drop_ivs += drop_VLE_ivs
    drop_ivs += drop_fused_raw

    if classification_mode == 'multi':
        y = df['final_result']
    elif classification_mode == 'pass_fail':
        y = df['final_result'].replace({0: 0, 1: 0, 2: 1, 3: 1})
    elif classification_mode == 'dropout':
        y = df['final_result'].replace({1: 1, 0: 0, 2: 0, 3: 0})
    elif classification_mode == 'drop_fail_pass':
        y = df['final_result'].replace({1: 0, 0: 1, 2: 2, 3: 2})
    else:
        raise ValueError("Invalid classification_mode. Choose from ['multi', 'pass_fail', 'dropout', 'drop_fail_pass']")

    X = df[[col for col in df.columns if col not in drop_ivs]]
    return X, y


def run_model_RF_weighted(df, course_name='RF_AAA', classification_mode='dropout'):
    from sklearn.preprocessing import label_binarize
    import shap
    import os
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    from sklearn.model_selection import train_test_split, GridSearchCV
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report, roc_auc_score
    from sklearn.metrics import cohen_kappa_score, matthews_corrcoef


    # Train-test split
    df_train, df_test = train_test_split(df, test_size=0.2, random_state=101, stratify=df['final_result'])

    X_train, y_train = get_x_y(df_train, classification_mode)
    X_test, y_test = get_x_y(df_test, classification_mode)

   
    # class_weights_options = [
    #     None,
    #     'balanced',
    #     {0: 1, 1: 1.5},
    #     {0: 1, 1: 2},
    #     {0: 1, 1: 3},
    #     {0: 1, 1: 4}
    # ]
    class_weights_options = [
     
        'balanced',
       
    ]
    param_grid = {
    'n_estimators': [400, 500, 600],
    'max_features': ['sqrt', 'log2'],
    'max_depth': [5, 7],
    'min_samples_split': [6, 8, 10, 12],
    'bootstrap': [True, False],
    'random_state': [18],
    'class_weight': class_weights_options 
}

    

    print("\n Performing grid search")
    gs = GridSearchCV(RandomForestClassifier(), param_grid=param_grid, cv=5, scoring='f1_weighted', n_jobs=-1)
    gs.fit(X_train, y_train)
    best_model = gs.best_estimator_

    print("\nBest Parameters Found:")
    print(gs.best_params_)

    # Prediction on the test set
    y_pred = best_model.predict(X_test)
    y_proba = best_model.predict_proba(X_test)

    # AUC score
    classes = np.unique(y_test)
    if len(classes) == 2:
        auc = roc_auc_score(y_test, y_proba[:, 1])
    else:
        y_test_bin = label_binarize(y_test, classes=classes)
        auc = roc_auc_score(y_test_bin, y_proba, average="macro", multi_class="ovr")

    base_wd = os.path.normpath(os.getcwd())
    out_dir = os.path.join(base_wd, f"outputs/models/{course_name}/{classification_mode}")
    os.makedirs(out_dir, exist_ok=True)

    # Save model predict
    y_df = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred}).join(X_test)
    y_df.to_csv(os.path.join(out_dir, "rq1_y_predict.csv"), index=False)

    import joblib

    # Save model
    model_path = os.path.join(out_dir, "rf_model.pkl")
    joblib.dump(best_model, model_path)

    feature_names = list(X_train.columns)
    with open(os.path.join(out_dir, "rf_features.txt"), "w") as f:
        f.write("\n".join(feature_names))
    print(f"\n[INFO] RandomForest model saved to: {model_path}")

    results = {
        'f1_score_macro': f1_score(y_test, y_pred, average='macro'),
        'f1_score_weighted': f1_score(y_test, y_pred, average='weighted'),
        'accuracy': accuracy_score(y_test, y_pred),
        'auc_score': auc,
        'kappa_score': cohen_kappa_score(y_test, y_pred),
        'mcc_score': matthews_corrcoef(y_test, y_pred),
        'confusion_matrix': confusion_matrix(y_test, y_pred),
        'importances': {f: imp for f, imp in zip(X_train.columns, best_model.feature_importances_)}
    }


    pd.DataFrame.from_dict(results.items()).to_csv(os.path.join(out_dir, "rq1_results.csv"))

    print(f"\n[{course_name} - {classification_mode}] Evaluation:")
    print(f"Macro F1 score:    {results['f1_score_macro']:.4f}")
    print(f"Weighted F1 score: {results['f1_score_weighted']:.4f}")
    print(f"Accuracy:          {results['accuracy']:.4f}")
    print(f"AUC Score:         {results['auc_score']:.4f}")
    print("Confusion Matrix:")
    print(results['confusion_matrix'])
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))
    print("\nTop 10 Feature Importances:")
    for feat, imp in sorted(results['importances'].items(), key=lambda x: x[1], reverse=True)[:10]:
        print(f"{feat:<30s}: {imp:.6f}")

 
    print("\n SHAP values")
    X_sub = shap.utils.sample(X_test, min(1500, len(X_test)), random_state=42)
    explainer = shap.Explainer(best_model, X_sub)
    shap_values = explainer(X_sub, check_additivity=False)

    for class_idx in range(shap_values.values.shape[2]):
        shap_class = shap.Explanation(
            values=shap_values.values[:, :, class_idx],
            base_values=shap_values.base_values[:, class_idx],
            data=shap_values.data,
            feature_names=shap_values.feature_names,
        )
        plt.clf()
        shap.plots.beeswarm(shap_class, show=False)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"beeswarm_class{class_idx}.png"))

    for class_idx in range(min(4, shap_values.values.shape[2])):
        shap_single = shap.Explanation(
            values=shap_values.values[0, :, class_idx],
            base_values=shap_values.base_values[0, class_idx],
            data=shap_values.data[0],
            feature_names=shap_values.feature_names,
        )
        plt.clf()
        shap.plots.waterfall(shap_single, show=False)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, f"waterfall_sample0_class{class_idx}.png"))
        plt.close()


In [ ]:
#balanced
stage_dict = {
    '0': df0_DDD,
    '25': df25_DDD,
    '50': df50_DDD,
    '75': df75_DDD
}

for stage, df in stage_dict.items():
    print(f"\n\nDropout Classification for Stage {stage}%")
    run_model_RF_weighted(df, course_name=f"RF_DDD_{stage}_change", classification_mode='dropout')

for stage, df in stage_dict.items():
    print(f"\n\npass_fail Classification for Stage {stage}%")
    run_model_RF_weighted(df, course_name=f"RF_DDD_{stage}_change", classification_mode='pass_fail')



Dropout Classification for Stage 0%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 6, 'n_estimators': 600, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_0_change/dropout\rf_model.pkl

[RF_DDD_0_change - dropout] Evaluation:
Macro F1 score:    0.5379
Weighted F1 score: 0.6611
Accuracy:          0.6385
AUC Score:         0.5838
Confusion Matrix:
[[379 160]
 [ 88  59]]

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.70      0.75       539
           1       0.27      0.40      0.32       147

    accuracy                           0.64       686
   macro avg       0.54      0.55      0.54       686
weighted avg       0.70      0.64      0.66       686


Top 10 Feature Importances:
imd_band                      : 0.308028
region                        : 0.303455


 99%|===================| 1357/1372 [01:42<00:01]        



Dropout Classification for Stage 25%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 500, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_25_change/dropout\rf_model.pkl

[RF_DDD_25_change - dropout] Evaluation:
Macro F1 score:    0.6216
Weighted F1 score: 0.7339
Accuracy:          0.7086
AUC Score:         0.7118
Confusion Matrix:
[[524 190]
 [ 67 101]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.73      0.80       714
           1       0.35      0.60      0.44       168

    accuracy                           0.71       882
   macro avg       0.62      0.67      0.62       882
weighted avg       0.78      0.71      0.73       882


Top 10 Feature Importances:
early_score_mean              : 0.344739
V_LPB                         : 0.132

100%|===================| 1758/1764 [01:55<00:00]        



Dropout Classification for Stage 50%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 8, 'n_estimators': 400, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_50_change/dropout\rf_model.pkl

[RF_DDD_50_change - dropout] Evaluation:
Macro F1 score:    0.5774
Weighted F1 score: 0.7733
Accuracy:          0.7433
AUC Score:         0.7204
Confusion Matrix:
[[563 152]
 [ 59  48]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.79      0.84       715
           1       0.24      0.45      0.31       107

    accuracy                           0.74       822
   macro avg       0.57      0.62      0.58       822
weighted avg       0.82      0.74      0.77       822


Top 10 Feature Importances:
early_score_mean              : 0.366565
V_LPB                         : 0.1273

 99%|===================| 1623/1644 [01:18<00:01]        



Dropout Classification for Stage 75%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 8, 'n_estimators': 400, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_75_change/dropout\rf_model.pkl

[RF_DDD_75_change - dropout] Evaluation:
Macro F1 score:    0.5478
Weighted F1 score: 0.8994
Accuracy:          0.8859
AUC Score:         0.6460
Confusion Matrix:
[[660  56]
 [ 30   8]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       716
           1       0.12      0.21      0.16        38

    accuracy                           0.89       754
   macro avg       0.54      0.57      0.55       754
weighted avg       0.91      0.89      0.90       754


Top 10 Feature Importances:
early_score_mean              : 0.283813
V_LPB                         : 0.1406

 99%|===================| 1494/1508 [01:00<00:00]        



pass_fail Classification for Stage 0%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 500, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_0_change/pass_fail\rf_model.pkl

[RF_DDD_0_change - pass_fail] Evaluation:
Macro F1 score:    0.5781
Weighted F1 score: 0.5838
Accuracy:          0.5860
AUC Score:         0.6142
Confusion Matrix:
[[154 155]
 [129 248]]

Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.50      0.52       309
           1       0.62      0.66      0.64       377

    accuracy                           0.59       686
   macro avg       0.58      0.58      0.58       686
weighted avg       0.58      0.59      0.58       686


Top 10 Feature Importances:
imd_band                      : 0.287873
highest_education             : 0.

 99%|===================| 1358/1372 [01:14<00:00]        



pass_fail Classification for Stage 25%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 500, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_25_change/pass_fail\rf_model.pkl

[RF_DDD_25_change - pass_fail] Evaluation:
Macro F1 score:    0.7433
Weighted F1 score: 0.7453
Accuracy:          0.7449
AUC Score:         0.8161
Confusion Matrix:
[[294 104]
 [121 363]]

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.74      0.72       398
           1       0.78      0.75      0.76       484

    accuracy                           0.74       882
   macro avg       0.74      0.74      0.74       882
weighted avg       0.75      0.74      0.75       882


Top 10 Feature Importances:
early_score_mean              : 0.495202
V_LPB                         :

 99%|===================| 1741/1764 [00:54<00:00]        



pass_fail Classification for Stage 50%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 8, 'n_estimators': 500, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_50_change/pass_fail\rf_model.pkl

[RF_DDD_50_change - pass_fail] Evaluation:
Macro F1 score:    0.7775
Weighted F1 score: 0.7825
Accuracy:          0.7810
AUC Score:         0.8636
Confusion Matrix:
[[269  69]
 [111 373]]

Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.80      0.75       338
           1       0.84      0.77      0.81       484

    accuracy                           0.78       822
   macro avg       0.78      0.78      0.78       822
weighted avg       0.79      0.78      0.78       822


Top 10 Feature Importances:
early_score_mean              : 0.444195
V_LPB                         : 

 99%|===================| 1629/1644 [02:40<00:01]        



pass_fail Classification for Stage 75%

 Performing grid search

Best Parameters Found:
{'bootstrap': True, 'class_weight': 'balanced', 'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 500, 'random_state': 18}

[INFO] RandomForest model saved to: c:\Users\zh_ch\Desktop\outputs/models/RF_DDD_75_change/pass_fail\rf_model.pkl

[RF_DDD_75_change - pass_fail] Evaluation:
Macro F1 score:    0.7858
Weighted F1 score: 0.7998
Accuracy:          0.7971
AUC Score:         0.8800
Confusion Matrix:
[[214  56]
 [ 97 387]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.79      0.74       270
           1       0.87      0.80      0.83       484

    accuracy                           0.80       754
   macro avg       0.78      0.80      0.79       754
weighted avg       0.81      0.80      0.80       754


Top 10 Feature Importances:
early_score_mean              : 0.369257
V_LPB                         :

100%|===================| 1501/1508 [03:06<00:00]        

In [5]:
def run_model_LR_weighted(df, course_name='LR_AAA', classification_mode='dropout'):
    import os
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import joblib
    import shap
    from sklearn.model_selection import train_test_split, GridSearchCV
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import (
        f1_score, accuracy_score, confusion_matrix, classification_report,
        roc_auc_score, cohen_kappa_score, matthews_corrcoef
    )
    from sklearn.preprocessing import label_binarize

    df_train, df_test = train_test_split(df, test_size=0.2, random_state=101, stratify=df['final_result'])
    X_train, y_train = get_x_y(df_train, classification_mode)
    X_test, y_test = get_x_y(df_test, classification_mode)

    class_weights_options = [
        
        'balanced'
    ]

    param_grid = {
        'C': [0.01, 0.1, 1, 10],
        'solver': ['liblinear'], 
        'class_weight': class_weights_options,
        'max_iter': [200]
    }

    print("\n Performing grid search for Logistic Regression")
    gs = GridSearchCV(LogisticRegression(), param_grid=param_grid, cv=5, scoring='f1_weighted', n_jobs=-1)
    gs.fit(X_train, y_train)
    best_model = gs.best_estimator_

    print("\n Best Parameters Found:")
    print(gs.best_params_)
    print("\n Best Class Weight:")
    print(gs.best_params_['class_weight'])

    y_pred = best_model.predict(X_test)
    y_proba = best_model.predict_proba(X_test)

    classes = np.unique(y_test)
    if len(classes) == 2:
        auc = roc_auc_score(y_test, y_proba[:, 1])
    else:
        y_test_bin = label_binarize(y_test, classes=classes)
        auc = roc_auc_score(y_test_bin, y_proba, average="macro", multi_class="ovr")

    out_dir = os.path.join(os.getcwd(), f"outputs/models/{course_name}/{classification_mode}")
    os.makedirs(out_dir, exist_ok=True)

    y_df = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred}).join(X_test)
    y_df.to_csv(os.path.join(out_dir, "rq1_y_predict.csv"), index=False)

    joblib.dump(best_model, os.path.join(out_dir, "lr_model.pkl"))
    with open(os.path.join(out_dir, "lr_features.txt"), "w") as f:
        f.write("\n".join(X_train.columns))

    results = {
        'f1_score_macro': f1_score(y_test, y_pred, average='macro'),
        'f1_score_weighted': f1_score(y_test, y_pred, average='weighted'),
        'accuracy': accuracy_score(y_test, y_pred),
        'auc_score': auc,
        'kappa_score': cohen_kappa_score(y_test, y_pred),
        'mcc_score': matthews_corrcoef(y_test, y_pred),
        'confusion_matrix': confusion_matrix(y_test, y_pred),
        'coefficients': dict(zip(X_train.columns, best_model.coef_[0]))
    }

    pd.DataFrame.from_dict(results.items()).to_csv(os.path.join(out_dir, "rq1_results.csv"))

    print(f"\n[{course_name} - {classification_mode}] Evaluation:")
    print(f"Macro F1 score:    {results['f1_score_macro']:.4f}")
    print(f"Weighted F1 score: {results['f1_score_weighted']:.4f}")
    print(f"Accuracy:          {results['accuracy']:.4f}")
    print(f"AUC Score:         {results['auc_score']:.4f}")
    print("Confusion Matrix:")
    print(results['confusion_matrix'])

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nTop 10 Feature Coefficients:")
    for feat, coef in sorted(results['coefficients'].items(), key=lambda x: abs(x[1]), reverse=True)[:10]:
        print(f"{feat:<30s}: {coef:.6f}")

   
    print("\n SHAP values")
    X_sub = shap.utils.sample(X_test, min(1500, len(X_test)), random_state=42)
    explainer = shap.Explainer(best_model, X_sub)

    shap_values = explainer(X_sub)

    shap_dir = os.path.join(out_dir, "shap")
    os.makedirs(shap_dir, exist_ok=True)
    
    plt.clf()
    shap.summary_plot(shap_values, X_sub, show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(shap_dir, "shap_beeswarm.png"))
    plt.close()

In [ ]:
#balanced
stage_dict = {
    '0': df0_DDD,
    '25': df25_DDD,
    '50': df50_DDD,
    '75': df75_DDD
}

for stage, df in stage_dict.items():
    print(f"\n\nDropout Classification for Stage {stage}%")
    run_model_LR_weighted(df, course_name=f"LR_DDD_{stage}_change", classification_mode='dropout')

for stage, df in stage_dict.items():
    print(f"\n\npass_fail Classification for Stage {stage}%")
    run_model_LR_weighted(df, course_name=f"LR_DDD_{stage}_change", classification_mode='pass_fail')



Dropout Classification for Stage 0%

 Performing grid search for Logistic Regression

 Best Parameters Found:
{'C': 0.01, 'class_weight': 'balanced', 'max_iter': 200, 'solver': 'liblinear'}

 Best Class Weight:
balanced

[LR_DDD_0_change - dropout] Evaluation:
Macro F1 score:    0.5544
Weighted F1 score: 0.6724
Accuracy:          0.6501
AUC Score:         0.5998
Confusion Matrix:
[[382 157]
 [ 83  64]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.71      0.76       539
           1       0.29      0.44      0.35       147

    accuracy                           0.65       686
   macro avg       0.56      0.57      0.55       686
weighted avg       0.71      0.65      0.67       686


Top 10 Feature Coefficients:
imd_band                      : -0.234305
disability                    : 0.225694
highest_education             : -0.098988
gender                        : -0.091720
region                        : 0.032746
age

In [7]:
def run_model_LightGBM_weighted(df, course_name='LGBM_AAA', classification_mode='dropout'):
    import os
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import joblib
    import shap
    import lightgbm as lgb
    from sklearn.model_selection import train_test_split, GridSearchCV
    from sklearn.metrics import (
        f1_score, accuracy_score, confusion_matrix, classification_report,
        roc_auc_score, cohen_kappa_score, matthews_corrcoef
    )
    from sklearn.preprocessing import label_binarize

    df_train, df_test = train_test_split(df, test_size=0.2, random_state=101, stratify=df['final_result'])
    X_train, y_train = get_x_y(df_train, classification_mode)
    X_test, y_test = get_x_y(df_test, classification_mode)

    class_weights_options = [
      
        'balanced',
     ]
    
    param_grid = {
        'n_estimators': [100, 200],
        'learning_rate': [0.05, 0.1],
        'max_depth': [3, 5],
        'class_weight': class_weights_options
    }

    model = lgb.LGBMClassifier(random_state=42)

    print("\n grid search for LightGBM")
    gs = GridSearchCV(model, param_grid=param_grid, cv=5, scoring='f1_weighted', n_jobs=-1)
    gs.fit(X_train, y_train)

    best_model = gs.best_estimator_

    print("\n Best Parameters Found:")
    print(gs.best_params_)

    y_pred = best_model.predict(X_test)
    y_proba = best_model.predict_proba(X_test)

    classes = np.unique(y_test)
    if len(classes) == 2:
        auc = roc_auc_score(y_test, y_proba[:, 1])
    else:
        y_test_bin = label_binarize(y_test, classes=classes)
        auc = roc_auc_score(y_test_bin, y_proba, average="macro", multi_class="ovr")

    out_dir = os.path.join("outputs/models", course_name, classification_mode)
    os.makedirs(out_dir, exist_ok=True)

    y_df = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred}).join(X_test.reset_index(drop=True))
    y_df.to_csv(os.path.join(out_dir, "rq1_y_predict.csv"), index=False)

    joblib.dump(best_model, os.path.join(out_dir, "lgb_model.pkl"))
    with open(os.path.join(out_dir, "lgb_features.txt"), "w") as f:
        f.write("\n".join(X_train.columns))

    results = {
        'f1_score_macro': f1_score(y_test, y_pred, average='macro'),
        'f1_score_weighted': f1_score(y_test, y_pred, average='weighted'),
        'accuracy': accuracy_score(y_test, y_pred),
        'auc_score': auc,
        'kappa_score': cohen_kappa_score(y_test, y_pred),
        'mcc_score': matthews_corrcoef(y_test, y_pred),
        'confusion_matrix': confusion_matrix(y_test, y_pred),
        'feature_importance': dict(zip(X_train.columns, best_model.feature_importances_))
    }

    pd.DataFrame.from_dict(results.items()).to_csv(os.path.join(out_dir, "rq1_results.csv"), index=False)

    print(f"\n[{course_name} - {classification_mode}] Evaluation:")
    print(f"Macro F1 score:    {results['f1_score_macro']:.4f}")
    print(f"Weighted F1 score: {results['f1_score_weighted']:.4f}")
    print(f"Accuracy:          {results['accuracy']:.4f}")
    print(f"AUC Score:         {results['auc_score']:.4f}")
    print("Confusion Matrix:")
    print(results['confusion_matrix'])

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nTop 10 Feature Importance:")
    for feat, imp in sorted(results['feature_importance'].items(), key=lambda x: abs(x[1]), reverse=True)[:10]:
        print(f"{feat:<30s}: {imp:.6f}")

    print("\n SHAP values")
    X_sub = shap.utils.sample(X_test, min(1500, len(X_test)), random_state=42)
    explainer = shap.Explainer(best_model, X_sub)
    shap_values = explainer(X_sub, check_additivity=False)


    shap_dir = os.path.join(out_dir, "shap")
    os.makedirs(shap_dir, exist_ok=True)

    plt.clf()
    shap.summary_plot(shap_values, X_sub, show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(shap_dir, "shap_beeswarm.png"))
    plt.close()

    plt.clf()
    shap.plots.bar(shap_values, show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(shap_dir, "shap_bar.png"))
    plt.close()

    plt.clf()
    idx = 0 
    shap.plots.waterfall(shap_values[idx], show=False)
    plt.tight_layout()
    plt.savefig(os.path.join(shap_dir, f"shap_waterfall_sample{idx}.png"))
    plt.close()




In [ ]:

#balanced
stage_dict = {
    '0': df0_DDD,
    '25': df25_DDD,
    '50': df50_DDD,
    '75': df75_DDD
}

for stage, df in stage_dict.items():
    print(f"\n\nDropout Classification for Stage {stage}%")
    run_model_LightGBM_weighted(df, course_name=f"LightGBM_DDD_{stage}_change", classification_mode='dropout')

for stage, df in stage_dict.items():
    print(f"\n\npass_fail Classification for Stage {stage}%")
    run_model_LightGBM_weighted(df, course_name=f"LightGBM_DDD_{stage}_change", classification_mode='pass_fail')



Dropout Classification for Stage 0%

 grid search for LightGBM
[LightGBM] [Info] Number of positive: 590, number of negative: 2154
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000537 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 35
[LightGBM] [Info] Number of data points in the train set: 2744, number of used features: 6
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] 

 98%|===================| 672/686 [00:13<00:00]        



Dropout Classification for Stage 25%

 grid search for LightGBM
[LightGBM] [Info] Number of positive: 670, number of negative: 2855
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000790 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1291
[LightGBM] [Info] Number of data points in the train set: 3525, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -

 97%|=================== | 859/882 [00:13<00:00]       



Dropout Classification for Stage 50%

 grid search for LightGBM
[LightGBM] [Info] Number of positive: 425, number of negative: 2862
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000904 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1304
[LightGBM] [Info] Number of data points in the train set: 3287, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

 97%|=================== | 794/822 [00:13<00:00]       



Dropout Classification for Stage 75%

 grid search for LightGBM
[LightGBM] [Info] Number of positive: 151, number of negative: 2864
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000986 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1310
[LightGBM] [Info] Number of data points in the train set: 3015, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -

 94%|=================== | 707/754 [00:11<00:00]       



pass_fail Classification for Stage 0%

 grid search for LightGBM
[LightGBM] [Info] Number of positive: 1507, number of negative: 1237
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000685 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 35
[LightGBM] [Info] Number of data points in the train set: 2744, number of used features: 6
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[Light

In [9]:
def run_model_DFFNN_weighted(df,
                              course_name='DFFNN_AAA',
                              classification_mode='dropout',
                              class_weight_option=None 
                             ):
    import os
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import joblib
    import shap
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.metrics import (
        f1_score, accuracy_score, confusion_matrix, classification_report,
        roc_auc_score, cohen_kappa_score, matthews_corrcoef
    )
    from sklearn.utils.class_weight import compute_class_weight
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Dense, Dropout
    from tensorflow.keras.callbacks import EarlyStopping

    def prepare_dffnn_data(df, classification_mode):
        X, y = get_x_y(df, classification_mode)
        feature_names = X.columns.tolist()
        scaler = MinMaxScaler()
        X_scaled = scaler.fit_transform(X)
        y_encoded = y.values.reshape(-1, 1)
        return X_scaled, y_encoded, feature_names, np.unique(y)

    def build_dffnn(input_dim, output_dim=1):
        model = Sequential()
        model.add(Dense(128, input_dim=input_dim, activation='relu'))
        model.add(Dropout(0.3))
        model.add(Dense(64, activation='relu'))
        model.add(Dropout(0.3))
        model.add(Dense(output_dim, activation='sigmoid'))
        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model

    df_train, df_test = train_test_split(df, test_size=0.2, random_state=101, stratify=df['final_result'])
    X_train, y_train, feature_names, class_names = prepare_dffnn_data(df_train, classification_mode)
    X_test, y_test, _, _ = prepare_dffnn_data(df_test, classification_mode)

    if class_weight_option is None:
        class_weight_dict = None
    elif class_weight_option == 'balanced':
        class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train.flatten()), y=y_train.flatten())
        class_weight_dict = dict(enumerate(class_weights))
    elif isinstance(class_weight_option, dict):
        class_weight_dict = class_weight_option
    else:
        raise ValueError("Error")

    model = build_dffnn(input_dim=X_train.shape[1])
    es = EarlyStopping(monitor='val_accuracy', patience=20, restore_best_weights=True)

    model.fit(X_train, y_train, epochs=200, batch_size=32,
              validation_split=0.1, callbacks=[es], verbose=1,
              class_weight=class_weight_dict)

    y_pred = model.predict(X_test).flatten()
    y_pred_label = (y_pred > 0.5).astype(int)
    y_true_label = y_test.flatten()

    auc = roc_auc_score(y_true_label, y_pred)
    results = {
        'f1_score_macro': f1_score(y_true_label, y_pred_label, average='macro'),
        'f1_score_weighted': f1_score(y_true_label, y_pred_label, average='weighted'),
        'accuracy': accuracy_score(y_true_label, y_pred_label),
        'auc_score': auc,
        'confusion_matrix': confusion_matrix(y_true_label, y_pred_label)
    }

    out_dir = os.path.join("outputs/models", course_name, classification_mode)
    os.makedirs(out_dir, exist_ok=True)
    pd.DataFrame({'y_true': y_true_label, 'y_pred': y_pred_label}).to_csv(os.path.join(out_dir, "dffnn_predictions.csv"), index=False)
    pd.DataFrame.from_dict(results.items()).to_csv(os.path.join(out_dir, "dffnn_results.csv"))
    model.save(os.path.join(out_dir, "dffnn_model.h5"))
    with open(os.path.join(out_dir, "dffnn_features.txt"), "w") as f:
        f.write("\n".join(feature_names))

    print(f"\n[{course_name} - {classification_mode}] Evaluation:")
    print(f"Macro F1 score:    {results['f1_score_macro']:.4f}")
    print(f"Weighted F1 score: {results['f1_score_weighted']:.4f}")
    print(f"Accuracy:          {results['accuracy']:.4f}")
    print(f"AUC Score:         {results['auc_score']:.4f}")
    print("Confusion Matrix:")
    print(results['confusion_matrix'])
    print("\nClassification Report:")
    print(classification_report(y_true_label, y_pred_label))


In [10]:
stage_dict = {
    '0': df0_DDD,
    '25': df25_DDD,
    '50': df50_DDD,
    '75': df75_DDD
}

class_weights_options = [
  
    'balanced',
    
]

classification_mode = 'dropout' 

for stage, df in stage_dict.items():
    for weight in class_weights_options:
        print(f"\n Stage {stage}%  Weight: {weight} =")

        model_name = f"DFFNN_DDD_{stage}_balanced"
        
        run_model_DFFNN_weighted(
            df,
            course_name=model_name,
            classification_mode=classification_mode,
            class_weight_option=weight
        )



 Stage 0%  Weight: balanced =


d:\anaconda\envs\text_analytics\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4063 - loss: 0.6973 - val_accuracy: 0.6945 - val_loss: 0.6619
Epoch 2/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6303 - loss: 0.6894 - val_accuracy: 0.5673 - val_loss: 0.6909
Epoch 3/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5931 - loss: 0.6838 - val_accuracy: 0.6364 - val_loss: 0.6699
Epoch 4/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5167 - loss: 0.6873 - val_accuracy: 0.6545 - val_loss: 0.6552
Epoch 5/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6028 - loss: 0.6794 - val_accuracy: 0.5782 - val_loss: 0.6888
Epoch 6/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6350 - loss: 0.6812 - val_accuracy: 0.6109 - val_loss: 0.6811
Epoch 7/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5961 - loss: 0.6703 - val_accuracy: 0.6364 - val_loss: 0.6670
Epoch 8/200
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5736 - loss: 0.7006 - val_accuracy: 0.5927 - 


[DFFNN_DDD_0_balanced - dropout] Evaluation:
Macro F1 score:    0.5534
Weighted F1 score: 0.7052
Accuracy:          0.7114
AUC Score:         0.5939
Confusion Matrix:
[[448  91]
 [107  40]]

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       539
           1       0.31      0.27      0.29       147

    accuracy                           0.71       686
   macro avg       0.56      0.55      0.55       686
weighted avg       0.70      0.71      0.71       686


 Stage 25%  Weight: balanced =


d:\anaconda\envs\text_analytics\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6495 - loss: 0.6881 - val_accuracy: 0.7224 - val_loss: 0.6440
Epoch 2/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6509 - loss: 0.6671 - val_accuracy: 0.7847 - val_loss: 0.5751
Epoch 3/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6908 - loss: 0.6628 - val_accuracy: 0.7139 - val_loss: 0.5963
Epoch 4/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6362 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.6513
Epoch 5/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6497 - loss: 0.6388 - val_accuracy: 0.6176 - val_loss: 0.6404
Epoch 6/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6335 - loss: 0.6442 - val_accuracy: 0.6771 - val_loss: 0.6107
Epoch 7/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6414 - loss: 0.6271 - val_accuracy: 0.7252 - val_loss: 0.5907
Epoch 8/200
100/100 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6603 - loss: 0.6334 - val_acc

d:\anaconda\envs\text_analytics\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)



[DFFNN_DDD_25_balanced - dropout] Evaluation:
Macro F1 score:    0.5841
Weighted F1 score: 0.7546
Accuracy:          0.7664
AUC Score:         0.6487
Confusion Matrix:
[[630  84]
 [122  46]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       714
           1       0.35      0.27      0.31       168

    accuracy                           0.77       882
   macro avg       0.60      0.58      0.58       882
weighted avg       0.75      0.77      0.75       882


 Stage 50%  Weight: balanced =
Epoch 1/200
93/93 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.6189 - loss: 0.6738 - val_accuracy: 0.5258 - val_loss: 0.7068
Epoch 2/200
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5890 - loss: 0.6718 - val_accuracy: 0.7295 - val_loss: 0.6095
Epoch 3/200
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5761 - loss: 0.6638 - val_accuracy: 0.8085 - val_loss: 0.5382
Epoch 4/200
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 7


[DFFNN_DDD_50_balanced - dropout] Evaluation:
Macro F1 score:    0.5627
Weighted F1 score: 0.7590
Accuracy:          0.7238
AUC Score:         0.6970
Confusion Matrix:
[[547 168]
 [ 59  48]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.77      0.83       715
           1       0.22      0.45      0.30       107

    accuracy                           0.72       822
   macro avg       0.56      0.61      0.56       822
weighted avg       0.81      0.72      0.76       822


 Stage 75%  Weight: balanced =
Epoch 1/200


d:\anaconda\envs\text_analytics\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


85/85 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8644 - loss: 0.6827 - val_accuracy: 0.7185 - val_loss: 0.6485
Epoch 2/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7575 - loss: 0.6437 - val_accuracy: 0.5563 - val_loss: 0.6780
Epoch 3/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6871 - loss: 0.6408 - val_accuracy: 0.6391 - val_loss: 0.6489
Epoch 4/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6582 - loss: 0.6579 - val_accuracy: 0.6358 - val_loss: 0.6469
Epoch 5/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6663 - loss: 0.6280 - val_accuracy: 0.6755 - val_loss: 0.6080
Epoch 6/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6574 - loss: 0.6250 - val_accuracy: 0.7450 - val_loss: 0.5473
Epoch 7/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6490 - loss: 0.6633 - val_accuracy: 0.7781 - val_loss: 0.5110
Epoch 8/200
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7190 - loss: 0.6413 - val_accuracy: 0.6623 - val_loss: 0.6


[DFFNN_DDD_75_balanced - dropout] Evaluation:
Macro F1 score:    0.4956
Weighted F1 score: 0.8361
Accuracy:          0.7798
AUC Score:         0.6299
Confusion Matrix:
[[577 139]
 [ 27  11]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.81      0.87       716
           1       0.07      0.29      0.12        38

    accuracy                           0.78       754
   macro avg       0.51      0.55      0.50       754
weighted avg       0.91      0.78      0.84       754



unseen datasets test

In [11]:
import joblib
import pandas as pd
import os
from sklearn.metrics import classification_report, roc_auc_score
import shap
import matplotlib.pyplot as plt

def test_model_on_unseen(model_path, df_list, stage_list, classification_mode='dropout'):
    model = joblib.load(model_path)

    feature_path = os.path.join(os.path.dirname(model_path), "lgb_features.txt")  # 改这里
    with open(feature_path, "r") as f:
        trained_features = f.read().splitlines()

    for df, stage in zip(df_list, stage_list):
        print(f"\n Testing on Stage {stage}% ")

        X_test, y_test = get_x_y(df, classification_mode)

        for feat in trained_features:
            if feat not in X_test.columns:
                X_test[feat] = 0
        X_test = X_test[trained_features]

        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)

        # AUC
        auc = roc_auc_score(y_test, y_proba[:, 1]) if len(model.classes_) == 2 else None

        print(classification_report(y_test, y_pred))
        if auc:
            print(f"AUC Score: {auc:.4f}")

        try:
            print(f"Running SHAP on Stage {stage}% ...")
            shap_dir = os.path.join(os.path.dirname(model_path), f"shap_on_C_stage{stage}")
            os.makedirs(shap_dir, exist_ok=True)
            X_sub = shap.utils.sample(X_test, min(1500, len(X_test)), random_state=42)
            explainer = shap.Explainer(model, X_sub)
            shap_values = explainer(X_sub, check_additivity=False)

            plt.clf()
            shap.summary_plot(shap_values, X_sub, show=False)
            plt.tight_layout()
            plt.savefig(os.path.join(shap_dir, "shap_beeswarm.png"))
            plt.close()

            plt.clf()
            shap.plots.bar(shap_values, show=False)
            plt.tight_layout()
            plt.savefig(os.path.join(shap_dir, "shap_bar.png"))
            plt.close()

            plt.clf()
            shap.plots.waterfall(shap_values[0], show=False)
            plt.tight_layout()
            plt.savefig(os.path.join(shap_dir, "shap_waterfall_sample0.png"))
            plt.close()
        except Exception as e:
            print(f"SHAP failed on stage {stage}: {e}")
    


In [12]:

df_list = [df0_CCC, df25_CCC, df50_CCC, df75_CCC]
stage_list = [0, 25, 50, 75]

base_model_name = "LightGBM_DDD"
classification_mode = "dropout"


for df, stage in zip(df_list, stage_list):
   
    model_path = f"D:/myx/Data science project·/outputs/models/{base_model_name}_{stage}_change/{classification_mode}/lgb_model.pkl"
    print(f"\n\nTesting {base_model_name}_{stage} on Course C ")

    test_model_on_unseen(
        model_path=model_path,
        df_list=[df],        
        stage_list=[stage],     
        classification_mode=classification_mode
    )




Testing LightGBM_DDD_0 on Course C 

 Testing on Stage 0% 
              precision    recall  f1-score   support

           0       0.71      0.64      0.67      1895
           1       0.34      0.41      0.37       839

    accuracy                           0.57      2734
   macro avg       0.52      0.53      0.52      2734
weighted avg       0.60      0.57      0.58      2734

AUC Score: 0.5286
Running SHAP on Stage 0% ...


100%|===================| 1496/1500 [00:13<00:00]        



Testing LightGBM_DDD_25 on Course C 

 Testing on Stage 25% 
              precision    recall  f1-score   support

           0       0.84      0.76      0.80      2158
           1       0.37      0.49      0.42       612

    accuracy                           0.70      2770
   macro avg       0.61      0.63      0.61      2770
weighted avg       0.74      0.70      0.72      2770

AUC Score: 0.6874
Running SHAP on Stage 25% ...


Testing LightGBM_DDD_50 on Course C 

 Testing on Stage 50% 
              precision    recall  f1-score   support

           0       0.90      0.87      0.88      2169
           1       0.29      0.34      0.31       334

    accuracy                           0.80      2503
   macro avg       0.59      0.60      0.60      2503
weighted avg       0.81      0.80      0.81      2503

AUC Score: 0.6970
Running SHAP on Stage 50% ...


Testing LightGBM_DDD_75 on Course C 

 Testing on Stage 75% 
              precision    recall  f1-score   support

      

 98%|===================| 1477/1500 [00:11<00:00]       

In [13]:

df_list = [df0_CCC, df25_CCC, df50_CCC, df75_CCC]
stage_list = [0, 25, 50, 75]

base_model_name = "LightGBM_DDD"
classification_mode = "pass_fail"


for df, stage in zip(df_list, stage_list):
   
    model_path = f"D:/myx/Data science project·/outputs/models/{base_model_name}_{stage}_change/{classification_mode}/lgb_model.pkl"
    print(f"\n\nTesting {base_model_name}_{stage} on Course C ")

    test_model_on_unseen(
        model_path=model_path,
        df_list=[df],          
        stage_list=[stage],   
        classification_mode=classification_mode
    )




Testing LightGBM_DDD_0 on Course C 

 Testing on Stage 0% 
              precision    recall  f1-score   support

           0       0.57      0.45      0.50      1337
           1       0.56      0.68      0.62      1397

    accuracy                           0.57      2734
   macro avg       0.57      0.56      0.56      2734
weighted avg       0.57      0.57      0.56      2734

AUC Score: 0.5861
Running SHAP on Stage 0% ...


Testing LightGBM_DDD_25 on Course C 

 Testing on Stage 25% 
              precision    recall  f1-score   support

           0       0.67      0.79      0.73      1245
           1       0.80      0.69      0.74      1525

    accuracy                           0.73      2770
   macro avg       0.74      0.74      0.73      2770
weighted avg       0.74      0.73      0.73      2770

AUC Score: 0.8232
Running SHAP on Stage 25% ...


Testing LightGBM_DDD_50 on Course C 

 Testing on Stage 50% 
              precision    recall  f1-score   support

         

In [14]:

df_list = [df0_FFF, df25_FFF, df50_FFF, df75_FFF]
stage_list = [0, 25, 50, 75]

base_model_name = "LightGBM_DDD"
classification_mode = "dropout"


for df, stage in zip(df_list, stage_list):
   
    model_path = f"D:/myx/Data science project·/outputs/models/{base_model_name}_{stage}_change/{classification_mode}/lgb_model.pkl"
    print(f"\n\nTesting {base_model_name}_{stage} on Course F")

    test_model_on_unseen(
        model_path=model_path,
        df_list=[df],         
        stage_list=[stage],   
        classification_mode=classification_mode
    )



Testing LightGBM_DDD_0 on Course F

 Testing on Stage 0% 
              precision    recall  f1-score   support

           0       0.84      0.62      0.71      4411
           1       0.21      0.46      0.29       972

    accuracy                           0.59      5383
   macro avg       0.53      0.54      0.50      5383
weighted avg       0.73      0.59      0.64      5383

AUC Score: 0.5549
Running SHAP on Stage 0% ...


 95%|=================== | 1421/1500 [00:11<00:00]       



Testing LightGBM_DDD_25 on Course F

 Testing on Stage 25% 
              precision    recall  f1-score   support

           0       0.88      0.82      0.85      4807
           1       0.23      0.32      0.27       804

    accuracy                           0.75      5611
   macro avg       0.55      0.57      0.56      5611
weighted avg       0.79      0.75      0.77      5611

AUC Score: 0.6272
Running SHAP on Stage 25% ...


Testing LightGBM_DDD_50 on Course F

 Testing on Stage 50% 
              precision    recall  f1-score   support

           0       0.92      0.87      0.90      4813
           1       0.12      0.20      0.15       426

    accuracy                           0.82      5239
   macro avg       0.52      0.54      0.52      5239
weighted avg       0.86      0.82      0.84      5239

AUC Score: 0.6059
Running SHAP on Stage 50% ...


Testing LightGBM_DDD_75 on Course F

 Testing on Stage 75% 
              precision    recall  f1-score   support

         

In [15]:

df_list = [df0_FFF, df25_FFF, df50_FFF, df75_FFF]
stage_list = [0, 25, 50, 75]

base_model_name = "LightGBM_DDD"
classification_mode = "pass_fail"


for df, stage in zip(df_list, stage_list):
   
    model_path = f"D:/myx/Data science project·/outputs/models/{base_model_name}_{stage}_change/{classification_mode}/lgb_model.pkl"
    print(f"\n\n Testing {base_model_name}_{stage} on Course F ")

    test_model_on_unseen(
        model_path=model_path,
        df_list=[df],          
        stage_list=[stage],   
        classification_mode=classification_mode
    )



 Testing LightGBM_DDD_0 on Course F 

 Testing on Stage 0% 
              precision    recall  f1-score   support

           0       0.48      0.62      0.54      2168
           1       0.68      0.56      0.61      3215

    accuracy                           0.58      5383
   macro avg       0.58      0.59      0.58      5383
weighted avg       0.60      0.58      0.58      5383

AUC Score: 0.6038
Running SHAP on Stage 0% ...


 Testing LightGBM_DDD_25 on Course F 

 Testing on Stage 25% 
              precision    recall  f1-score   support

           0       0.65      0.63      0.64      2215
           1       0.76      0.78      0.77      3396

    accuracy                           0.72      5611
   macro avg       0.70      0.70      0.70      5611
weighted avg       0.72      0.72      0.72      5611

AUC Score: 0.7716
Running SHAP on Stage 25% ...


 Testing LightGBM_DDD_50 on Course F 

 Testing on Stage 50% 
              precision    recall  f1-score   support

      